### ISSUE TITLE
Strange build error since image update

### ISSUE THREAD

**Issue by plenderj** [aws/aws-lambda-base-images#108]
I use CDK to deploy a number of Python3.9 lambdas. These automagically use Docker under the hood for bundling, a là:

```
_lambda.PythonLayerVersion(self,
                           layer_name,
                           entry=layer_folder,
                           compatible_runtimes=[Runtime.PYTHON_3_9],
                           compatible_architectures=[Architecture.ARM_64],
                           bundling={
                               'image': DockerImage('public.ecr.aws/sam/build-python3.9:latest-arm64'),
                               'asset_hash_type': AssetHashType.SOURCE
                           },
                           removal_policy=RemovalPolicy.RETAIN)

```

Since this commit https://github.com/aws/aws-lambda-base-images/commit/7b74cd773b6d1e85589bf95b11e5b0ebcd7a38de my Docker-based builds seem to be broken in a bizarre manner for one function which depends on Zeep, which depends on lxml and a bunch of other xml and xslt-related binaries.

```
Collecting zeep
  Downloading zeep-4.2.1-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.2/101.2 KB 2.3 MB/s eta 0:00:00
Collecting lxml>=4.6.0
  Downloading lxml-4.9.3.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 8.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.9.3.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]

```

The requirements.txt for that particular lambda just contains 'zeep'

If I create a Dockerfile which extends public.ecr.aws/sam/build-python3.9:latest-arm64 and yum installs the aforementioned development packages, the build succeeds and CDK triggers CFN to deploy. But the lambda itself is broken as it's now missing a whole host of .so files

```
Runtime.ImportModuleError: Unable to import module 'StripeWebhookReceiver': libxslt.so.1: cannot open shared object file: No such file or directory

Runtime.ImportModuleError: Unable to import module 'StripeWebhookReceiver': libicuuc.so.72: cannot open shared object file: No such file or directory
```

**Comment by plenderj** [comment]
This was a complete coincidence. Thank you to AWS support for helping me out-of-band of this issue.

I am building for arm64 and whilst the python base image was updated recently it was a red herring: lxml was _also_ updated recently and it looks like a bunch of arm64 compiled .so files are missing (or removed?) from the latest version. Adding a pinned version of lxml to the previous version resolved this.

Repro failure steps. If I have a requirements.txt which consists of:

```
zeep
```

or 

```
lxml
zeep
```

Then it'll fetch lxml 4.9.3 which will bork:

```
Collecting requests-file>=1.5.1
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Collecting lxml>=4.6.0
  Downloading lxml-4.9.3.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 8.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.9.3.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
```

However if I pin to lxml 4.9.2:

```
lxml==4.9.2
zeep
```

Then it happily builds without issue

**Comment by jtuliani** [comment]
Thanks for closing out the issue @plenderj
