### ISSUE TITLE
Java 21 (Corretto) Runtime

### ISSUE THREAD

**Issue by SentryMan** [aws/aws-lambda-base-images#113]
Java 21 is GA, so might as well make an issue to track this. I'll see you guys next year.

**Comment by jtuliani** [comment]
We have published a preview AWS Lambda base container image for Java 21 ([here](https://gallery.ecr.aws/lambda/java)). You can use this image to build and deploy Java 21 Lambda functions if using container images as your function deployment format.

This image is tagged ‘preview’ and should not be used for production workloads. We invite you to provide your feedback on this preview image below. We are aiming to provide GA support for Java 21 in Lambda, as both a base container image and a managed runtime, by the end of 2023.

The Java 21 image is based on the [provided.al2023 preview image](https://github.com/aws/aws-lambda-base-images/issues/92#issuecomment-1737531040). Note the use of microdnf as the package manager when updating your Dockerfiles to use this preview.

**Comment by jtuliani** [comment]
Lambda now supports Java 21 as a managed runtime as base container image: https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/

There's no blog post for this release, the only new features are from the Java 21 language enhancements, and the shift from Amazon Linux 2 to [Amazon Linux 2023](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/)

Please share any feedback.
