### ISSUE TITLE
Latest public.ecr.aws/lambda/java:11 aws-lambda-java-serialization-0.2.0.jar jackson packages not relocated.

### ISSUE THREAD

**Issue by treyfarmigoni** [aws/aws-lambda-base-images#119]
The jar located in /var/runtime/lib/aws-lambda-java-serialization-0.2.0.jar seems to have changed from previous versions. 

The old package layout from a previous container version is below 
(everything is relocated under `com.amazonaws.lambda.thirdparty...` )
![Screenshot 2023-10-19 at 9 15 57 AM](https://github.com/aws/aws-lambda-base-images/assets/39505090/713dd31d-84a1-4d36-8a48-88ef843c6cd6)

However, with the latest jar, it seems that some of the jackson packages are no longer relocated, causing the real version to never be loaded. 
![Screenshot 2023-10-19 at 9 16 12 AM](https://github.com/aws/aws-lambda-base-images/assets/39505090/f3f4a04f-6a21-4b59-b360-e2819e9cd281)

This eventually causes issues when performing jackson serialization such as:
![Screenshot 2023-10-19 at 9 20 18 AM](https://github.com/aws/aws-lambda-base-images/assets/39505090/a6b1a326-4b71-4817-8866-167a28eaef3d)

**Comment by GustafNi** [comment]
Had this issue as well. They seem to have pushed new base image to docker, so new image builds work. 
I was using the public.ecr.aws/lambda/java:17 .

**Comment by smirnoal** [comment]
right, new images with the fix have been published. Thanks for your patience
