### ISSUE TITLE
Node.js 20.x. Longer cold starts than prior versions (18,16) with 3X top values compared to the average 

### ISSUE THREAD

**Issue by adriantanasa** [aws/aws-lambda-base-images#126]
The recently released nodejs20.x runtime for AWS Lambda is establishing a concerning performance degradation trend for Node runtime and larger variation in the cold start values with maximum values 3X more than previous node version.

Based on running a [benchmark](https://medium.com/@adtanasa/size-is-almost-all-that-matters-for-optimizing-aws-lambda-cold-starts-cad54f65cbb) over 100 points for a function (1KB code size, 256MB memory, us-east-1) with nodejs20.x runtime the **average value is 240ms** (compared to 171ms node18.x and 159ms for node16.x).

There is an increased variation in the initDuration for this runtime compared to the previous version, with the maximum values increased by several times. For the same 1KB-sized function, its **maximum cold start value** is now **793ms compared to 248ms** (node18), and the **P90 is 584ms** compared to 182ms on node18.

This "instability" is confirmed for functions with variable package sizes (1K to 64MB) over 1000 cold start executions.

<img width="989" alt="Screenshot 2023-11-21 at 12 52 38" src="https://github.com/aws/aws-lambda-base-images/assets/5277071/f25e4984-4a59-4d9d-a4a0-52f926f4c820">

Gist results for all Nodejs runtimes:

- [nodejs20.x](https://gist.github.com/adriantanasa/06a9cbc36744ef0bf946255e9e75efbe)
- [nodejs18.x](https://gist.github.com/adriantanasa/d9cb9f7313f985f180c0aec98e482f2b)
- [nodejs16.x](https://gist.github.com/adriantanasa/95f5298ae7977e8d81f26c2c2c798bf0)

Details of how the benchmark is designed and executed here: [Size is (almost) all that matters for optimizing AWS Lambda cold starts](https://medium.com/@adtanasa/size-is-almost-all-that-matters-for-optimizing-aws-lambda-cold-starts-cad54f65cbb)

This issue was raised also by  @o-alexandrov  on the [Nodejs20.x release](https://github.com/aws/aws-lambda-base-images/issues/91) topic:

> @jtuliani I was very hyped about Node.js 20 [after your comment above](https://github.com/aws/aws-lambda-base-images/issues/91#issuecomment-1737694321) on what AWS did to decrease cold starts.
> Unfortunately, [the cold starts are `a lot worse` than Node.js 18/16/14 for non-Graviton (non-ARM) and pretty much the same as Node.js 16 for Graviton](https://maxday.github.io/lambda-perf/).
>_Originally posted by @o-alexandrov in https://github.com/aws/aws-lambda-base-images/issues/91#issuecomment-1814696834_

Hopefully, this is something that can be tuned in the next while to fulfill the high community expectations from the announcement of cold starts optimization actions such as the removal of extra root CA certs, lazy-loading of non-essential modules, and further tuning of the AWS SDK 3 library.

![runtime-nodejs20](https://github.com/aws/aws-lambda-base-images/assets/5277071/7e04e3b6-5501-4872-b861-ef449849e8af)

**Comment by o-alexandrov** [comment]
A new alternative to `@aws-sdk/*` just came out: [see performance page of aws-lite](https://aws-lite.org/performance).
@jtuliani is it time to consider a Node.js managed runtime w/o `@aws-sdk/*`?

**Comment by electricsheep** [comment]
I have experienced the same issue.

Here is a graph of my lambda duration - red line indicates the upgrade from nodejs18.x to nodejs20.x:

![image](https://github.com/aws/aws-lambda-base-images/assets/686835/8a7c3ad4-4c6d-4bea-b3b1-e63a41ed6c9d)

Runtime average for v18: 195ms
Runtime average for v20: 310ms

**Comment by adriantanasa** [comment]
I have run the benchmark recently and it seems the peak Init Duration issues are fixed now. I am curios what caused them though. Also the overall performance is improved almost matching the nodejs16.x runtime, You can see here the latest results for nodejs20.x. Great job, AWS team for addressing this ;) 

![screencapture-us-east-1-console-aws-amazon-cloudwatch-home-2024-03-14-16_00_26](https://github.com/aws/aws-lambda-base-images/assets/5277071/a381c264-d351-4508-af23-85a386a669cd)

PS @electricsheep please create another issue for your case. It might be something from the libraries used or other factor. This issue here was only for Init Duration with fairly plain functions with no npm libraries or AWS SDK calls.
