### ISSUE TITLE
Bug: dnf command does not work on version of public.ecr.aws/lambda/python:3.11-x86_64 publish around 2023.12.05 16:00 UTC

### ISSUE THREAD

**Issue by loesak** [aws/aws-lambda-base-images#127]
### Description:
We've been using the image `public.ecr.aws/lambda/python:3.11-x86_64` for building our Python based Lambda ZIP artifacts for use by the AWS Lambda Python 3.11 runtime. We are not using the image for building other Docker images for running a Docker based AWS Lambda runtimes (please let me know if this is not a supported use case for this Docker image). However, I believe this is an issue for also building subsequent Docker images. It seems recently the base image was updated and the deprecated `yum` command is no longer present and the `dnf` command should be used instead to install OS packages. However, when running the `dnf` command, results in an error.

```
dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
```

This is preventing us from installing needed dependencies we need for performing our build but I assume it would also be needed to install any OS packages for any Docker image based off this image.

### Steps to reproduce:
Start a container based on this image:
```
docker run --rm -it --entrypoint /bin/bash public.ecr.aws/lambda/python:3.11-x86_64
```
or to pin to the image where this issue was discovered:
```
docker run --rm -it --entrypoint /bin/bash public.ecr.aws/lambda/python@sha256:9c593e44c6936fd4335405ab3e3dea55f6a38cab5c009a43cc7e01c2e3eef81e
```

then try to run the `dnf` command:
```
bash-5.2# dnf --help
dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)

bash-5.2# dnf install zip
dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
```

### Observed result:
```
dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
```

### Expected result:
Expected `dnf` command to execute successfully w/o error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
None

**Comment by lehmat** [comment]
Another symptom: The `libffi` package seems to be missing when building pip packages.

```
#9 3.740         File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
#9 3.740         File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
#9 3.740         File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
#9 3.740         File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
#9 3.740         File "<frozen importlib._bootstrap_external>", line 940, in exec_module
#9 3.740         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#9 3.740         File "/tmp/pip-build-env-941f5u0c/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 27, in <module>
#9 3.740           from .macosx_libfile import calculate_macosx_platform_tag
#9 3.740         File "/tmp/pip-build-env-941f5u0c/overlay/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 43, in <module>
#9 3.740           import ctypes
#9 3.740         File "/var/lang/lib/python3.11/ctypes/__init__.py", line 8, in <module>
#9 3.740           from _ctypes import Union, Structure, Array
#9 3.740       ImportError: libffi.so.6: cannot open shared object file: No such file or directory
#9 3.740       [end of output]
#9 3.740   
#9 3.740   note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sidneyaraujomelo** [comment]
I'm facing the same issue.

**Comment by BenTuttlePG** [comment]
I am getting an import issue that seems related. 

```
curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
{"errorMessage": "Unable to import module 'lambda_function': libffi.so.6: cannot open shared object file: No such file or directory", "errorType": "Runtime.ImportModuleError", "requestId": "52221d6d-ebcc-45ea-b6b9-0aed04af0ce1", "stackTrace": []}%   
```

The same code works on the 3.10 image.

**Comment by miguelzetina** [comment]
Same issue with my Dockerfile: 

```
FROM public.ecr.aws/lambda/python:3.11
RUN dnf install -y gcc-c++ postgresql-devel
```

Running `docker build .` I got this:

![image](https://github.com/aws/aws-lambda-base-images/assets/11604205/52f731ad-c598-4913-8c9f-912dd55ce79b)

**Comment by ranman** [comment]
from `readelf` on the symbols in `liblzma.so.5` - the `5.2.2` version exists but not the `5.2` version

`librpmio.so.9` seems to be linked against `5.2`

in the 3.12 branch this issue is not present it uses the same `librpm.so.9` but it has an updated `liblzma.so.5` that has the 5.2 versions there.

This is what python3.12 (working) looks like:
```
Version definition section '.gnu.version_d' contains 3 entries:
 Addr: 0x0000000000001f80  Offset: 0x00001f80  Link: 6 (.dynstr)
  000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: liblzma.so.5
  0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: XZ_5.0
  0x0038: Rev: 1  Flags: none  Index: 3  Cnt: 2  Name: XZ_5.2
  0x0054: Parent 1: XZ_5.0
```

This is what python3.11 (not working) looks like:
```
  Version definition section '.gnu.version_d' contains 4 entries:
   Addr: 0x0000000000001d90  Offset: 0x00001d90  Link: 4 (.dynstr)
    000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: liblzma.so.5
    0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: XZ_5.0
    0x0038: Rev: 1  Flags: none  Index: 3  Cnt: 2  Name: XZ_5.1.2alpha
    0x0054: Parent 1: XZ_5.0
    0x005c: Rev: 1  Flags: none  Index: 4  Cnt: 2  Name: XZ_5.2.2
    0x0078: Parent 1: XZ_5.1.2alpha
```

**Comment by lantrix** [comment]
> Another symptom: The `libffi` package seems to be missing when building pip packages.
> 

We also have the missing `libffi` package breaking when installing requirements (building pip packages) on this base lambda layer `public.ecr.aws/lambda/python:3.11`

**Comment by nikkipin** [comment]
The python runtime team is aware of the issue, and has root caused the problem. They'll be triggering a rollback in several hours during business hours in Dublin.

For now, please utilize the previous Python3.11 image

**Comment by lantrix** [comment]
> The python runtime team is aware of the issue, and has root caused the problem. They'll be triggering a rollback in several hours during business hours in Dublin.
> 
> For now, please utilize the previous Python3.11 image

Thanks for that. Looking at the [public ECR gallery](https://gallery.ecr.aws/lambda/python), I never realised that pinning to tag `3.11` would mean it is rebuilt, with breaking changes.

> `public.ecr.aws/lambda/python:3.11` was built **13 hours ago** and is 168MB

Thanks for the advice to pin to specific builds, e.g. `public.ecr.aws/lambda/python:3.11.2023.11.18.02` which was built 18 days ago and was 238 MB

**Comment by LewisCowlesMotive** [comment]
I've linked an issue nobody will be able to read in a private project. Basically, the current `3.11` is broken due to missing shared-object files. It wasn't broken yesterday...

Does anyone know if AWS publishes list of libc compatibility, because if we can't use their image and hope they provide libc compatibility, I'm not sure if it's safe to build our own image and expect to have no possibility of errors. One of my worries is that they continue this, so we have to build including shared objects elsewhere and then that is incompatible with a version of shared library where we want to run. With the specific libffi release it's not even like we could get our code to build in-situ.

**Comment by jtuliani** [comment]
We have published an updated Python 3.11 image which addresses this issue. Our apologies for any inconvenience caused.

**Comment by victor-teran-rs-old** [comment]
Hi, we have been trying to do it today without success, and we are getting this error

```
Status: Downloaded newer image for amazon/aws-lambda-python:3.11.2023.12.06.11
+ WORKING_DIRECTORY=/var/task
+ echo /var/task
+ dnf group install -y 'Development tools'
setup/aws_dependencies.sh: line 10: dnf: command not found
```
We are creating the env in a GitHub actions workflow.

**Comment by Stigjb** [comment]
I think they did a rollback, the latest `3.11` tag has `yum` but not `dnf`
