### ISSUE TITLE
Yum Not Available in Python 3.11 Image

### ISSUE THREAD

**Issue by mjtieman** [aws/aws-lambda-base-images#128]
Yum is not available in the latest Python 3.11 image, `public.ecr.aws/lambda/python:3.11.2023.12.05.16`.

Command to reproduce the issue:
```
docker run -it --entrypoint yum public.ecr.aws/lambda/python:3.11.2023.12.05.16 --help
```

Output:
```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "yum": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by hugobcar** [comment]
I'm facing the same error. In `python:3.10`  this error doesn't happen.

It's weird because `3.11` images were recently updated:

![image](https://github.com/aws/aws-lambda-base-images/assets/10134807/b2123d94-ad27-42f4-a00e-97b75b19a849)

https://gallery.ecr.aws/lambda/python

**Comment by hugobcar** [comment]
I would say to you use `dfn`  instead of `yum` but `dfn` is not working in `3.11`

https://github.com/aws/aws-lambda-base-images/issues/127

**Comment by mjtieman** [comment]
The workaround I'm using is building from the previous image, `public.ecr.aws/lambda/python:3.11.2023.11.18.02`.

**Comment by kylebechtel77** [comment]
Same issue with python3.11, previous image also uses arch for me. Strange.

**Comment by pjacobr** [comment]
We are having similar issues with our deployment. Things not building and getting this:

```
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

When pip installing bs4, pymeeus

**Comment by anthony-rolland** [comment]
Having a similar issue. I was able to temporarily resolve the issue by rolling back the image tag to another version.

**Comment by gebailey** [comment]
Looks like the underlying image was constructed from Amazon Linux 2 for the last known working images vs. Amazon Linux 2023 for the current, broken image...

**Comment by gebailey** [comment]
Also, this [blog post](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/) says:

> With the launch of provided.al2023 you can migrate your AL2 custom runtime-based Lambda functions right away. It also sets the foundation of future Lambda managed runtimes. The future releases of managed language runtimes such as Node.js 20, Python 3.12, Java 21, and .NET 8 are based on Amazon Linux 2023 and will use provided.al2023 as the base image.

Which seems to imply that while the Python 3.12 runtime would be based on Amazon Linux 2023, the older ones would continue to use Amazon Linux 2.

**Comment by dkruszew** [comment]
Error message that I get when calling `dnf` within the latest `public.ecr.aws/lambda/python:3.11` image:

```dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)```

**Comment by yennick-investre** [comment]
> Error message that I get when calling `dnf` within the latest `public.ecr.aws/lambda/python:3.11` image:
> 
> `` dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9) ``

I was able to reproduce this same error.

**Comment by jimgar** [comment]
> > Error message that I get when calling `dnf` within the latest `public.ecr.aws/lambda/python:3.11` image:
> > `` dnf: /var/lang/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9) ``
> 
> I was able to reproduce this same error.

Me three

**Comment by jtuliani** [comment]
Thanks @mjtieman for flagging. We can confirm the issue. A fix is in progress. I will post an update when it is released. In the meantime, as a workaround please use the previous Python 3.11 image as discussed above.

**Comment by IgorSiilva** [comment]
I'm facing the same issue, and i'm also getting this error too.
`Unable to import module 'main': libffi.so.6: cannot open shared object file: No such file or directory`

**Comment by jtuliani** [comment]
We have published an updated Python 3.11 image which addresses this issue. Our apologies for any inconvenience caused.

**Comment by tb102122** [comment]
@jtuliani 

so we would need to use `dnf update -y` to resolve security issues?
https://alas.aws.amazon.com/AL2/ALAS-2023-2350.html

**Comment by jtuliani** [comment]
@tb102122 as with earlier Python 3.11 images, and all AL2-based images, you should use yum rather than dnf. 

dnf should be used for images based on Amazon Linux 2023. For Python, our first AL2023-based image will be Python 3.12.
