### ISSUE TITLE
Ruby 3.3 support

### ISSUE THREAD

**Issue by mudge** [aws/aws-lambda-base-images#136]
As [Ruby 3.3.0 was released](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/) on 25 Dec 2023, would it be possible to provide a new Lambda base image with it?

It looks like the latest update to https://gallery.ecr.aws/lambda/ruby was 5 days ago with Ruby 3.2 as the latest version.

**Comment by jtuliani** [comment]
Hi @mudge and Happy New Year. Support for Ruby 3.3 is currently scheduled for March 2024, see https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-future

We will provide further updates here as we progress.

**Comment by jtuliani** [comment]
Ruby 3.3 support in AWS Lambda was released on 2024-04-04: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-lambda-ruby-3-3/
