### ISSUE TITLE
How to install Amazon Linux 2023 package security fixes in new python 3.12 image?

### ISSUE THREAD

**Issue by christianplatta1012** [aws/aws-lambda-base-images#140]
Hi,
we migrated our docker lambda deployment to the new Python 3.12 image and adjusted everything we needed (e.g. changing yum to the dnf symlinked microdnf). The ECR image scan is complaining about 4 MEDIUM security findings:

ALAS2023-2024-472 | curl-minimal:8.3.0-1.amzn2023.0.2
ALAS2023-2024-472 | libcurl-minimal:8.3.0-1.amzn2023.0.2
ALAS2023-2024-466 | ncurses-base:6.2-4.20200222.amzn2023.0.4
ALAS2023-2024-466 | ncurses-libs:6.2-4.20200222.amzn2023.0.4

We do a microdnf upgrade --refresh in all off our images but it does not seem to do anything.
It just says:
Downloading metadata...
Nothing to do.

How can I make microdnf install all the available security patches?

The ECR Security Scan description says that patches are available and when I download the public.ecr.aws/amazonlinux/amazonlinux:2023-minimal image, a newer version of curl is installed in this image.
How can I install those patched versions in the python 3.12 image?

Best regards,
Christian

**Comment by deyvsh** [comment]
FWIW we've just run across this and tentatively concluded that the frequency of new base image releases from AWS is such that we don't need to run additional package updates at docker build time. In fact I think it's better (for us) not to, because it makes builds more repeatable. We still scan at build time and monitor what's in prod, so we should see issues if there are any. Would like to hear alternative/dissenting positions though.

**Comment by christianplatta1012** [comment]
We do microdnf upgrade only for our base image which is then used in all of our application images to make builds more repeatable. The above issues where fixed after approximately 3 days in the base images. I think it would still be nice to be able to apply existing updates manually imho... Do I have to configure dnf to a different repository manually or something like that?

**Comment by andclt** [comment]
Hello,
As mentioned in the previous message, we've released updated ECR images that address the CVEs. What you have observed appears to be a behaviour of `micro-dnf`. Our team is actively investigating this issue.
 
As a temporary workaround, you can resolve this by removing the following file:
```
rm /etc/dnf/vars/releasever
```

Afterward, execute the following command:
```
dnf --refresh update --releasever=latest
```

**Comment by christianplatta1012** [comment]
This works! There was a security finding today (ALAS2023-2024-520 | openssl-libs:1:3.0.8-1.amzn2023.0.10) and with the commands described above I was able to install the latest versions with security patches!

**Comment by michaelact** [comment]
Is there a way to just upgrade security dependencies in microdnf?
