### ISSUE TITLE
Base NodeJS 14 Docker image contains known security vulnerabilities

### ISSUE THREAD

**Issue by volphy** [aws/aws-lambda-base-images#18]
My Docker image based on the Docker image:
amazon/aws-lambda-nodejs:14

contains a few known security vulnerabilities:
- https://alas.aws.amazon.com/AL2/ALAS-2021-1652.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1653.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1655.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1656.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1662.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1664.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1669.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1677.html

I know that as a workaround I could update affected packages in my Docker image:
```
RUN yum install -y \
    glib2 \
    curl \
    glibc \
    glibc-all-langpacks \
    glibc-common \
    glibc-minimal-langpack \
    libcrypt \
    libcurl \
    libxml \
    libxml2 \
    nss \
    nss-sysinit \
    python \
    python-libs \
    bzip2-libs 
```

However, I think that the official base Docker images from AWS should already be patched.

**Comment by volphy** [comment]
Similar issue https://github.com/aws/aws-lambda-base-images/issues/19

**Comment by carlzogh** [comment]
Thanks @volphy - this has been resolved (see: https://github.com/aws/aws-lambda-base-images/issues/19#issuecomment-874722252)
