### ISSUE TITLE
Base Python 3.8 Docker image contains known security vulnerabilities

### ISSUE THREAD

**Issue by volphy** [aws/aws-lambda-base-images#19]
My Docker image based on the Docker image:
amazon/aws-lambda-python:3.8

contains a few known security vulnerabilities:
- https://alas.aws.amazon.com/AL2/ALAS-2021-1652.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1653.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1655.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1656.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1662.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1664.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1669.html
- https://alas.aws.amazon.com/AL2/ALAS-2021-1677.html

I know that as a workaround I could update affected packages in my Docker image:
```
RUN yum install -y \
    glib2 \
    curl \
    glibc \
    glibc-all-langpacks \
    glibc-common \
    glibc-minimal-langpack \
    libcrypt \
    libcurl \
    libxml \
    libxml2 \
    nss \
    nss-sysinit \
    python \
    python-libs \
    bzip2-libs 
```
However, I think that the official base Docker images from AWS should already be patched.

**Comment by volphy** [comment]
Similar issue: https://github.com/aws/aws-lambda-base-images/issues/18

**Comment by carlzogh** [comment]
Hey @volphy - thanks for reaching out! 
Our automation has just released new revisions of these base images that have pulled in the latest patches for these vulnerabilities 😊
