### ISSUE TITLE
Node 22 LTS Released

### ISSUE THREAD

**Issue by faradaytrs** [aws/aws-lambda-base-images#212]
https://nodejs.org/en/blog/release/v22.11.0
Do you have any roadmap to support it?

**Comment by e965** [comment]
+1 really waiting too, literally the only thing stopping me from upgrading projects to node 22

**Comment by leandrodamascena** [comment]
Hey @faradaytrs and @e965! According to the [official Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-future), Node 22 support in Lambda is expected this month, but may be subject to change.

![image](https://github.com/user-attachments/assets/5fe638c8-231e-492b-af56-85f4dd967acd)

**Comment by e965** [comment]
As far as I can see, version 22 is already available in the registry

![image](https://github.com/user-attachments/assets/0fc56f3e-8b94-4f77-84c1-41d05a1848ef)

**Comment by jtuliani** [comment]
We have completed our launch of Node.js 22 to all regions. Congrats to those who spotted some components early :)

https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-support-nodejs-22/
https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/
