### ISSUE TITLE
Broken docker pull from public.ecr.aws

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-lambda-base-images#220]
Is this team responsible for pushing images up to public.ecr.aws?

If so…

```bash
docker pull public.ecr.aws/lambda/provided:al2023
```

With the response:

```plain
Error response from daemon: failed to resolve reference "public.ecr.aws/lambda/provided:al2023": unexpected status from HEAD request to https://public.ecr.aws/v2/lambda/provided/manifests/al2023: 403 Forbidden
```

Anyone else seeing this? I don't have anything for `public.ecr.aws` in my `~/.docker/config` file.

**Comment by leandrodamascena** [comment]
Hello @skyzyx! Thinking here that maybe you may have some blocks on your network or was this a temporary error? I managed to pull the image just now.

Can you please try again?

```sh
docker pull public.ecr.aws/lambda/provided:al2023
al2023: Pulling from lambda/provided
569cc7a04d3d: Pull complete 
9d72fb16d46c: Pull complete 
60d60f0796ad: Pull complete 
0943ac8b622e: Pull complete 
Digest: sha256:1bcfd1c03e1eca6357e55042c34d4ac5ab61e6786e2015ef57030036f03d9b96
Status: Downloaded newer image for public.ecr.aws/lambda/provided:al2023
public.ecr.aws/lambda/provided:al2023
```

**Comment by skyzyx** [comment]
It's been happening for about a week. Just tried it again and got the same error.

Did you try from _inside_ the Amazon network, or _outside_ the Amazon network?

**Comment by leandrodamascena** [comment]
Both network and worked! Did you log into ECR Public by any chance? Did you try `docker logout public.ecr.aws` and try pulling again?

**Comment by skyzyx** [comment]
That was it. Weird. I didn't know that you could even login to `public.ecr.aws` or when I would have done it.

Thanks!

**Comment by leandrodamascena** [comment]
> That was it. Weird. I didn't know that you could even login to `public.ecr.aws` or when I would have done it.
> 
> 
> 
> Thanks!

Wow cool! It could be some script or something else that left an invalid/expired public ecr credential in your environment and then running the logout command cleared it.
