### ISSUE TITLE
What's the ETA of dotnet6.0 image?

### ISSUE THREAD

**Issue by kevbite** [aws/aws-lambda-base-images#27]
.NET 6 was released this week, was wondering what the ETA of a dotnet6.0 base image for Lambda would be?

Thanks

**Comment by kevbite** [comment]
Linking issue which provides details of how you can build the dotnet6 lambda container image yourself
https://github.com/aws/aws-lambda-dotnet/issues/889

**Comment by timdinhdotcom** [comment]
Is there instruction on how to build the image on MacOS?

**Comment by ckcks12** [comment]
@timdinhdotcom 
you can run Powershell on macOS :)

```bash
brew install --cask powershell
git clone git@github.com:aws/aws-lambda-base-images --depth 1
cd aws-lambda-base-images/LambdaRuntimeDockerfiles
pwsh build.ps1 -TargetFramework net6 -Architecture amd64
```

and you'd find the image
```bash
docker images | grep dotnet6-runtime
```

I aslo uploaded it for public.
`ckcks12/dotnet6-aws-lambda-runtime`

Here's my dockerfile.
```Dockerfile
FROM ckcks12/dotnet6-aws-lambda-runtime:6.0.100 as base

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o /app/build

FROM base as final
WORKDIR /var/task
COPY --from=build /app/build ./
CMD ["Program::Program.Function::Handle"]
```

I've tested it :)

**Comment by ckcks12** [comment]
@timdinhdotcom 
By the way I found this:  https://github.com/aws/aws-lambda-dotnet/commit/730e6c4394729a30502f6de277e7d0c8d06728ce

.net6 packaging with self-contained and `provided.al2` .... I haven't treid it yet but seems working ... and I think it's super better than container!

**Comment by funkel1989** [comment]
@ckcks12 Do you have a working lambda handler example file for .NET 6?

**Comment by glennawatson** [comment]
https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeListBucketsNET6 is the one I based it on @funkel1989

**Comment by ckcks12** [comment]
@funkel1989 

I just used `dotnet new lambda.image.EmptyFunction`

For minimal api (asp.net core) the only official way is using provided runtime which is less performant, tho. 
Because minimal api isn't based on HostBuilder/Startup, ApiGatewayProxyFunction cannot intantiate the minimal server.

**Comment by funkel1989** [comment]
@ckcks12  I was looking to do something similar to this:
https://github.com/Battle-Line-Productions/BattleNotifications/blob/main/BattleNotifications.Api/LambdaEntryPoint.cs

That's what I did for my dotnet 5 containers allowing me to due the config in the startup file and not have to build an entirely new handler. I haven't tried it yet but maybe I can just builder.UseStartup<Program>(); and everything will be happy still? I'll update here when I get a chance to figure this out. should be pretty simple.

**Comment by ckcks12** [comment]
@funkel1989
I also tried to find such a simple way. However I couldn't.

From .NET6, There's no such a `Startup` class. We build a `WebApplication` via `WebApplicationBuilder`. 
Maybe something like `builder.UseWebApplicationFactory<Program>()` would be the most likely way I guess.
Just like IntegrationTest.

**Comment by ckcks12** [comment]
Or we could create our own Proxy Function.
The fundamental is still simple. Only two things we sould implement are:

1. From APIGatewayEventRequest to HttpContext.Request
2. From HttpContext.Response to APIGatewayEventResponse

Actually these are all `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction` does.
However it's not simple, tho. I'd like to say it's tedious and annoying.
You can look into the implementation of `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction` and you will understand what i'm talking about.

So my conclusion is.. wait for AWS Official Support.
To be honest, AWS Lambda with container is less performant. Also it's bad DX. (compared to just uploading `zip`)

According to .NET Core 3.1 Release and AWS Support for it, 
It looks like at least `4 months` for supporting .NET 6.

**Comment by kevbite** [comment]
net 6 container image has been updated.

https://gallery.ecr.aws/lambda/dotnet

**Comment by timdinhdotcom** [comment]
I have tested both x86_x64 and arm64 image. arm64 is find, however, my server less app take a long time and then time out with the x86_64 image. Possible bad built. need more testing to determine exact cause
