### ISSUE TITLE
Which ECR Image is the latest for dot net 5?

### ISSUE THREAD

**Issue by nCubed** [aws/aws-lambda-base-images#41]
The [AWS ECR Gallery](https://gallery.ecr.aws/lambda/dotnet) has several dot net 5 images:
* public.ecr.aws/lambda/dotnet:5.0
* public.ecr.aws/lambda/dotnet:5.0.2022.03.16.07
* public.ecr.aws/lambda/dotnet:5.0.2022.03.16.14
* public.ecr.aws/lambda/dotnet:5.0.2022.03.16.19
* public.ecr.aws/lambda/dotnet:5.0.2022.03.16.22
* public.ecr.aws/lambda/dotnet:5.0.2022.03.19.00
* public.ecr.aws/lambda/dotnet:5.0.2022.03.19.07

Which image is the latest for dot net 5.0?
```
public.ecr.aws/lambda/dotnet:5.0
```
or
```
public.ecr.aws/lambda/dotnet:5.0.2022.03.19.07
```

If `public.ecr.aws/lambda/dotnet:5.0` is the latest, does that mean 5.0 will always have the latest security patches? Where the other versions are snapshots in time?

**Comment by carlzogh** [comment]
Hey @nCubed - that's correct, `public.ecr.aws/lambda/dotnet:5.0` is the rolling image tag reference that will always be updated with the latest available image for the Lambda .NET 5.0 runtime. The date-time tags are snapshots of images released on the date mentioned in the tag reference.

**Comment by nCubed** [comment]
@carlzogh - By chance is this in the documentation somewhere? I had looked in several places, but may have missed the info about the rolling image tag.

**Comment by jtuliani** [comment]
I don't think it is. I'll check, and get it added if needed. Thanks for flagging!
