### ISSUE TITLE
Update zlib in java11 Image to 1.2.7-19

### ISSUE THREAD

**Issue by bbemis017** [aws/aws-lambda-base-images#43]
Can someone update the zlib package in the [amazon/aws-lambda-java
 Image](https://hub.docker.com/layers/aws-lambda-java/amazon/aws-lambda-java/11/images/sha256-8ddf19ec7c6ef21f568a244f15f318ceab1d509516f5a4f79b2280c846744132?context=explore)?

Currently the Image is on version `zlib-1.2.7-18.amzn2.x86_64` which is being flagged as having a reported vulnerability in ECR [ALAS-2022-1772](https://alas.aws.amazon.com/AL2/ALAS-2022-1772.html).

I can work around it by adding `RUN yum -y update zlib` to my dockerfile but it's probably a good idea to update the image in docker as well

**Comment by h4xnoodle** [comment]
this seems to impact the nodejs image as well.

I actually ran `yum update -y` in it, and the scanner still raised a high alert after having -19 installed.

```
#7 15.53 Updated:
...                                      
#7 15.53   zlib.x86_64 0:1.2.7-19.amzn2.0.1  
```
