### ISSUE TITLE
Node v16 Unavailable

### ISSUE THREAD

**Issue by achuinard** [aws/aws-lambda-base-images#45]
shellscape, despite claiming he `got that 🔥 for all things node`, is sick of hearing about the continuous discussion on Node 16 AWS availability, so this is the new thread that [he asked us to open](https://github.com/aws/aws-lambda-base-images/issues/14) so we can continue to track the gaping hole that AWS has regarding which versions of Node can be used on Lambda.

**Comment by ealmiladi** [comment]
I suppose `got that 🔥 for all things node` is but only a temporary fire in one's heart.

Still looking for the lambda node16 base image, though.

**Comment by dl748** [comment]
@achuinard There was already one created in December #33 in case you were wondering

**Comment by joebowbeer** [comment]
Dup of #33
