### ISSUE TITLE
Latest Node 16 image (16.2022.08.22.13) is missing xargs 

### ISSUE THREAD

**Issue by JavaScriptBach** [aws/aws-lambda-base-images#57]
The following Dockerfile fails to build:

```
FROM public.ecr.aws/lambda/nodejs:16.2022.08.22.13 as base

RUN xargs --help
```

This is a regression from earlier versions e.g. [16.2022.08.18.09](https://hub.docker.com/layers/aws-lambda-nodejs/amazon/aws-lambda-nodejs/16.2022.08.18.09/images/sha256-9fad6e1a14542f0137dadfa746b3b495ecc8426b8c9ae0b683e7f7ca004f2962?context=explore).

If this is not a bug, is there documentation on what we can expect to have available in these base images?

**Comment by keshayad** [comment]
Thanks for reporting the issue. We're working on releasing the fix and there is a workaround available.
Please refer https://github.com/aws/aws-lambda-base-images/issues/58 for more details.

**Comment by keshayad** [comment]
We have released new set of base images with the fix, please consume the latest versions.
