### ISSUE TITLE
No amd64 image for node 14/14.2022.08.26.14

### ISSUE THREAD

**Issue by fengkaijia** [aws/aws-lambda-base-images#60]
The latest node 14 image (14.2022.08.26.14) only has arm64 build (`ba7ecd619742`). 

This is breaking our pipeline that is using `amazon/aws-lambda-nodejs:14` on x86.

**Comment by keshayad** [comment]
Hi, thanks for reporting this.
We're working on releasing the latest base image as soon as we can.
Apologies for the issue it caused.

**Comment by keshayad** [comment]
Hi, we have released fresh set of base images for both, `arm64` and `x86_64`.
