### ISSUE TITLE
Maintain separate NodeJS images for AWS SDK v2 and v3

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-lambda-base-images#69]
Not everyone wants to use AWS SDK for JS v3, and the pain of migrating off of v2 can be extreme. Can we add a separate image that maintains the usage of v2 from the 16.x image?

**Comment by CaerusKaru** [comment]
I understand v3 has been GA for a while, and there is a desire to incorporate it into a new base image, but personally for my team we will never use it in our products. I would like to avoid bundling the SDK myself, as we use the AWS CDK integration, which auto-sets `externs`, and this is a rough edge to have to redo in all of our apps as well.

My alternative here is simply rolling the image myself, which I really would prefer not to do, especially because the Lambda team already has the infrastructure set up to do this automatically. Can we please have a second image published? (or at the very least reach out to me internally so I can make use of the existing infrastructure for my team)

**Comment by jtuliani** [comment]
Couldn't find you internally, maybe you can find me?
