### ISSUE TITLE
Node.js `18.x`. Longer cold starts than prior versions (16, 14, 12)

### ISSUE THREAD

**Issue by o-alexandrov** [aws/aws-lambda-base-images#83]
Based on @jtuliani [comment from Nov 2022](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1327249479), AWS is aware of the longer cold starts:

> We're aware of the reports of longer cold starts on Node 18 and we're investigating the issue. We'll report back once those investigations are complete.

And then again from @jtuliani on [Feb 9, 2023](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1423915498):
> We have identified the primary cause of the longer cold starts in the Node 18 runtime as thread blocking in a dependency used during initialization. We are evaluating options to resolve this in a future Node 18 runtime update.

`@maxday` created a [Cold Start dashboard](https://maxday.github.io/lambda-perf/):

> 10 Cold Starts for each runtime, updated daily

Using `@maxday`'s dashboard, you could quickly verify the cold starts issue has not been resolved.

As mentioned by `@ffxsam` in [this comment](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1477887843), the issue might be related to the slower `aws-sdk v3` [described in this article](https://dev.to/aws-builders/benchmarking-the-aws-sdk-2pd4).
- prior node.js versions included aws-sdk v2, which according to the article above leads to faster cold starts than v3

**Comment by bicatu** [comment]
Hi @jtuliani is there a ticket we can follow to track the progress of this issue?
I am holding the migration to node18 of some services and it would be nice to know when to resume.

**Comment by jtuliani** [comment]
Thank you @o-alexandrov for filing this issue to track cold start performance improvements in the Lambda Node.js 18 runtime. We have identified several potential performance optimizations which we are evaluating and testing. We will provide updates via this issue once they are rolled out.

**Comment by aldex32** [comment]
Hi @jtuliani any update please?

**Comment by jtuliani** [comment]
Thank you for noticing @o-alexandrov  :)

Yes, we have deployed updates to the AWS Lambda Node.js18 runtime which bring the cold start times close to the performance with Node.js 16. We are continuing to investigate further optimizations. To reduce the risk of backward compatibility issues, any further optimizations will be focused on Node 20 rather than being back-ported to existing runtimes.

Therefore, closing this item.
