### ISSUE TITLE
Request: Post-mortem about delivery of Python 3.10 Lambda serverless runtime (#31)

### ISSUE THREAD

**Issue by HWiese1980** [aws/aws-lambda-base-images#93]
As suggested in #31, on behalf of all involved and affected I kindly request a detailed post-mortem report about what lead to the enormous delay. 

Python 3.10 was released in October 2021, more than one and a half year ago, and it took the delivery teams that long to deliver Python 3.10 as a Lambda Serverless runtime. 

AWS, please provide insights especially about what you are going to do in order to avoid such delays or worse for Python 3.11 and future versions. 

Thank you!

**Comment by jtuliani** [comment]
We have heard the feedback from this community and our customers directly regarding the need for prompt support of new language versions in AWS Lambda. We recognize that the delay in releasing support for Python 3.10 and other runtimes has fallen short of customer expectations. We apologize for the inconvenience this has caused.

We are working hard to address these delays--both to catch up with pending runtime launches and to avoid a recurrence in future. To do so, we are making substantial internal changes to the mechanisms and processes by which Lambda runtimes are both launched and patched.

We believe the best way to re-earn trust is to focus on consistent runtime delivery. We are also evaluating options to provide greater transparency into up-coming runtime releases. However, we do not believe it would be appropriate or useful for us to enter into a public discussion of the Lambda internals relating to runtime launches.

**Comment by HWiese1980** [comment]
Well, thank you for the short summary. I guess I speak for everyone when I say, I am very curious to see if that is going to work out next time. 

In all seriousness, I have been a software developer and engineer myself for more than 20 years now, and I do know the struggles and difficulties, and the pressure. I bet your developers did the best job possible given the circumstances. It is these circumstances that need change. And I am sure, as long as your management plays along, it is going to be fine in the end. I guess we will see. Good luck!
